version: '3.9'

services:
  api:
    build:
      context: ./api/
    depends_on:
      - "redis"
      - "db"
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend

  db:
    build:
      context: ./db/
    platform: linux/x86_64
    networks:
      - backend

  redis:
    image: redis
    networks:
      - backend

  client:
    build:
      context: ./client/
    ports:
      - 80:80
    networks:
      - frontend

  cdn:
    build:
      context: ./cdn/
    ports:
      - 8081:80
    networks:
      - frontend

networks:
  frontend:
    # use default network configuration
  backend:
    # use default network configuration
