"""
Magazine post type.
"""
type Post {
  "Title of the article."
  title: String!
  "First paragraph to be displayed in the thumbnails."
  firstParagraph: String!
  "Body of the article."
  article: String!
  "Authors first name."
  firstName: String!
  "Authors last name."
  lastName: String!
  "Date the post was created."
  created: String!
  "Date the post was last updated."
  updated: String
}
