CREATE TABLE IF NOT EXISTS Authors (
  authorId INT AUTO_INCREMENT,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (authorId)
);

CREATE TABLE IF NOT EXISTS Posts (
  postId INT AUTO_INCREMENT,
  authorId INT,
  title VARCHAR(255) NOT NULL,
  firstParagraph VARCHAR(255) NOT NULL,
  article TEXT NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (postId),
  FOREIGN KEY (authorId) REFERENCES Authors(authorId)
);
